services:
  perfumery_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-4001}
      POSTGRES_HOST: ${POSTGRES_URL:-fast_inspection_postgresql_db_server}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12134588ad}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-perfumery_db}
    ports:
      - '${PORT:-4001}:${PORT:-4001}'
    networks:
      - fast_inspection_network

networks:
  fast_inspection_network:
    name: fast_inspection_network
